on : 
  push:
    branches:
      - main 
name : ğŸš€ Implantar website em 
jobs push :
   web-deploy :
     name : ğŸ‰ Implementar 
    runs-on : ubuntu-latest 
    steps :
    - nome : ğŸšš Obtenha os 
      usos mais recentes do cÃ³digo : actions / checkout @ v2
    
    - nome : ğŸ“‚ Os arquivos de sincronizaÃ§Ã£o 
      usam : SamKirkland/FTP-Deploy-Action@4.1.0 
      com :
         servidor : ${{secrets.ftp_host}} 
        nome de usuÃ¡rio : ${{secrets.ftp_user}} 
        senha : ${{secrets.ftp_password}}
        server-dir : digitalnudge.org